from .dashboard import DashboardModule
from .placeholder import PlaceholderModule
from .settings_module import SettingsModule
from .lost_sample_finder import LostSampleFinderModule
from .sample_manager import SampleManagerModule
from .song_manager import SongManagerModule
from .kit_manager import KitManagerModule
from .synth_editor import SynthEditorModule
from .batch_hub import BatchHubModule
from .backup_sync import BackupSyncModule
